name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: 18.x
          
      - name: Install Dependencies
        run: npm install

      - name: Run Test
        run: echo 'npm run test'        

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: 18.x
          
      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build    

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
          
      - name: Deploy to Ec2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |  
            cd feedback-app
            git pull origin
            npm install
            npm run build
            sudo cp -r build/* /var/www/html
            sudo systemctl restart nginx